### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by alexpearce** [cernanalysispreservation/cap-client#81]
I tried using the client using the Python that ships with my Linux distribution, v3.6.5 but this failed:

```
$ cap-client --help
Traceback (most recent call last):
  File "/home/apearce/tmp/venv/bin/cap-client", line 11, in <module>
    load_entry_point('cap-client==0.0.2', 'console_scripts', 'cap-client')()
  File "/home/apearce/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/apearce/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/apearce/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/apearce/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/apearce/tmp/venv/lib/python3.6/site-packages/cap_client/cli/__init__.py", line 33, in <module>
    from cap_client.cap_api import CapAPI
  File "/home/apearce/tmp/venv/lib/python3.6/site-packages/cap_client/cap_api.py", line 30, in <module>
    from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'
```

I suspect there are probably other issues with Python 3 compatibility, but I haven't checked.

**Comment by alexpearce** [comment]
> the client is not compatible with Python 3

Yes, I figured :smile: I thought I'd open an issue just to track it, and for others who might try with Python 3 to see that it's a known problem.

**Comment by clelange** [comment]
Hi, is there any timescale to make the cap-client work with python3? Also, it would be nice if the instructions at https://cap-client.readthedocs.io/en/latest/ stated that cap-client only works with legacy python.

**Comment by pamfilos** [comment]
@clelange PR #83 has been created.. we will try and merge before the end of next week
